### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Keyboard' of undefined

### ISSUE THREAD

**Issue by roboflank** [loicknuchel/ionic-starter#5]
Great project here. I have tried to compile it but once installed it am running into an error. Seems to be an issue with keyboard plugin but in have installed all the required plugins.
The popup alert appears at the start of the application.
![screenshot_2016-01-07-11-54-16](https://cloud.githubusercontent.com/assets/6532631/12166276/d862110a-b535-11e5-8a14-185e47751d01.png)

**Comment by loicknuchel** [comment]
Hi, you should have the stack (with file & line number) in the console. Could you paste it here ?

It seems that the Keyboard is not found, I use it only on `www/app/common/plugins/keyboard.js` where I use `cordova.plugins.Keyboard`; which seems great according to this plugin doc : https://github.com/driftyco/ionic-plugin-keyboard

Are you sure to have it installed ?
Could you try : `ionic plugin list` ?

**Comment by roboflank** [comment]
The plugins are installed. The error is displayed on phone though nothing in the console.

**Comment by roboflank** [comment]
I updated the project to your recent commits,  it is okay now.

**Comment by loicknuchel** [comment]
Cool :D

**Comment by eldyvoon** [comment]
on Mac I do this `cordova plugin add ionic-plugin-keyboard`
